checked: "1"
time: 2
per_page: 15
size_limit: 400
n_5: 5
img_rule: "image/jpeg,image/gif,image/png"
user:
  name_length: 50
  email_length: 255
  pass_length: 6
  size_ava: 80
  size_ava_sm: 50
  size_ava_30: 30
micropost:
  length_max: 140
